Feature/restart
UniGameTeam/UniGame.Context pull request #2
Opened 2021-03-24 15:37 UTC by Glongooo

2021-03-26 10:46 UTC, Mefodei requested changes

2021-03-26 10:46 UTC, Mefodei commented on SerializableContext/Runtime/ContextDataSources/AsyncDataSources.cs
> +            if (source is LifetimeScriptableObject ltSO)
достаточно делать Is ILifeTimeContext или is ILifeTime

2021-03-26 12:06 UTC, HartMagic commented on SerializableContext/Runtime/Sources/SingleMonoBehaviourSource.cs
> +                (_instance as IDisposable)?.Dispose();
Тут два метода - OnDestroy и Dispose, выполняют одну и ту же функцию, поэтому, если монобех реализует IDisposable (что немного странно, как как dispose pattern у MonoBehaviour по умолчанию и так есть), то должно по умолчанию подразумеваться, что в OnDestroy у него вызовется Dispose, а то иначе что мне вызывать? Dispose? Или дестроить? Или оба?

2021-03-26 12:08 UTC, HartMagic commented on Runtime/Scriptable/AsyncContextDataSources.cs
> +            foreach (var source in sources)
вот тут неоднозначно, мы при активации все сорсы подписываем на лайфтайм, потом при ресете еще раз...если лайфтайм ресетится, то ссылка никуда не девается, и подвязывать надо один раз в итоге

2021-03-29 15:08 UTC, Glongooo commented on Runtime/Scriptable/AsyncContextDataSources.cs
> +            foreach (var source in sources)
В LifeTimeScriptableObject.Reset() вызывается lifeTimeDefinition.Release() в котором вызывается LifeTime.Release() в котором в свою очередь вызывается Dispose всех подвешенных IDisposable и очищаются все коллекции, тоесть после вызова Reset никаких ссылок в LifeTime не будет и нужно добавить их заново

2021-03-29 15:14 UTC, Glongooo commented on SerializableContext/Runtime/ContextDataSources/AsyncDataSources.cs
> +            if (source is LifetimeScriptableObject ltSO)
ILifeTimeContext не реализует IDisposable поэтому такая проверка не поможет, возможность приведения к LifeTimeScriptableObject неявным образом гарантируется типом AssetReferenceDataSource который расширяет AssetReferenceDataSource<LifetimeScriptableObject>

2021-03-30 13:13 UTC, merged